### ISSUE TITLE
Buttons in dummy microservice app are out of order

### ISSUE THREAD

**Issue by mattljiang** [oslabs-beta/Chronos#9]
**Describe the bug**
Buttons in dummy microservice app are out of order

**To Reproduce**
1. In the /examples/microservices folder, run `npm run dev`
2. Open up localhost:3000
3. Get orders/books/customers buttons are out of order

**Expected behavior**
Buttons match the microservice

**Screenshots**
![image](https://user-images.githubusercontent.com/9983876/106039470-01fe5600-608e-11eb-85d5-e01b6ecceaa3.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome

**Comment by mattljiang** [comment]
@DerekQuoc can you take a look at this when you're doing the NPM package? I haven't checked, but our Dummy gRPC app might also have this problem if we just copy-pasted.

**Comment by DerekQuoc** [comment]
@mattljiang As our I rewrote our buttons for the gRPC examples, the issue above does not apply to those examples.
